# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72dfb2e69911ff048bf4cc7adc7f746c0ee4138b80637f34aecbee9242c8c81f71c5169073872dd653f87b7f5a801b9252e44865c7aef6753634421a2a37d081

test:
  secret_key_base: 5877c55faeb3b6c6d4382a5dd67433f48f35ae8f3e06199f340831a75c673379f30a9fb3543563331e2c4801863b347cd13dc4e8873d29ee2e9d53aa6bc34b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
